### PR TITLE
Navigate to top button

### PR DESCRIPTION
**Pull request by pranavsuriya-sr**
## What is the change?
Added the navigate to top button for the index page.

## Related issue?
closes: #144 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm JWOC contributor.

##  Screenshots (if any)
https://user-images.githubusercontent.com/91081814/153838267-0274bda9-7439-4803-ac3e-4d57dd9c12e8.mp4

### CODE REVIEW

**Comment by Chaitalishetty** [comment]
@pranavsuriya-sr The scroll to top button should be shown once the page is scrolled until then it should be disabled.

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
@pranavsuriya-sr The scroll to top button should be shown once the page is scrolled until then it should be disabled.

**Comment by pranavsuriya-sr** [comment]
Made the button appear only after scrolling down from the home page.

https://user-images.githubusercontent.com/91081814/154002080-a2df74f4-f872-40ec-9487-ac1638333307.mp4

**Review by Chaitalishetty — APPROVED** [review]

**Comment by Chaitalishetty** [comment]
Amazing work 🤩!

**Pull request merged**
