### PR TITLE
Centered Banner and added favicon

### PR DESCRIPTION
**Pull request by developer-diganta**
## What is the change?
The home page banner is centered and occupies the visible viewport on opening. Also I have added a favicon.

## Related issue?
closes: #20

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

##  Screenshots (if any)
image
image

### CODE REVIEW

**Review by Mandar-Gajbhiye15 — APPROVED** [review]

**Comment by Chaitalishetty** [comment]
@developer-diganta  Can you update the branch and resolve the merge conficts . We are facing issue with merging

**Comment by developer-diganta** [comment]
I think it will work now..

**Review by Chaitalishetty — COMMENTED** [review]
The banner doesnot look centered

**Comment by developer-diganta** [comment]
image
Is this one looking OK?

**Comment by Chaitalishetty** [comment]
yes

**Review by Chaitalishetty — APPROVED** [review]

**Pull request merged**
