### PR TITLE
issue #6 Scrollbar-homepage changes

### PR DESCRIPTION
**Pull request by SayantaniDeb**
## What is the change?
changed the scrollbar and also made changes to the height of the homepage

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

##  Screenshots (if any)

https://user-images.githubusercontent.com/74983536/135582895-f64daf4d-9b67-4524-b776-8e573b694a26.mp4

### CODE REVIEW

**Review by Chaitalishetty — COMMENTED** [review]
Hey can you change the background-color of the scroll-thumb to either #f9713d OR #eb3750; so that is looks more bold

**Comment by SayantaniDeb** [comment]
https://user-images.githubusercontent.com/74983536/135614404-5e88ab47-a80c-4efa-8d7c-c56b8457da33.mp4

I've fixed

* navbar-made it sticky
* changed the background colour of the scroll thumb

**Review by Chaitalishetty — APPROVED** [review]

**Comment by Chaitalishetty** [comment]
@SayantaniDeb  Can you update the branch and resolve the merge conficts . We are facing issue with merging

**Comment by SayantaniDeb** [comment]
okay sure.

**Pull request merged**
