### PR TITLE
Preloader added

### PR DESCRIPTION
**Pull request by sorba160**
## What is the change?
I added a pre loader to the website.

## Related issue?
closes: Add Preloader #105

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm JWOC contributor.

### CODE REVIEW

**Comment by sorba160** [comment]
I have added the animated pre loader @Chaitalishetty . If there is any issue please tell me.
Thank you

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
@sorba160 This looks good . But can you make the loader gif based on the theme of the website.
Like you can do some animation with the logo or related to that.

**Comment by Chaitalishetty** [comment]
Also create a new branch while pushing to the repo so that you can branch out your code from main.

**Comment by sorba160** [comment]
> @sorba160 This looks good . But can you make the loader gif based on the theme of the website. Like you can do some animation with the logo or related to that.

Ok I am trying .

**Comment by sorba160** [comment]
> Also create a new branch while pushing to the repo so that you can branch out your code from I

**Pull request closed without merging**
