### PR TITLE
scrollbar removed for mobile view

### PR DESCRIPTION
**Pull request by mnnkhndlwl**
## What is the change?
I have successfully removed scrollbar for mobile view i have attached screenshots of before and after 

## Related issue?
closes: #107 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm JWOC contributor.

##  Screenshots (if any)
before
before
after
after

### CODE REVIEW

**Comment by mnnkhndlwl** [comment]
@Chaitalishetty please check it

**Review by Chaitalishetty — APPROVED** [review]
Good Job!

**Comment by Sanghu01** [comment]
I have successfully removed scrollbar for mobile view . plz check this zip file code
[HackClubRAIT-Website.github.io-remove_scrollbar.zip](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/files/7979728/HackClubRAIT-Website.github.io-remove_scrollbar.zip)

**Comment by Sanghu01** [comment]
BEFORE screenshot
image

**Comment by Sanghu01** [comment]
after screenshot

image

**Pull request merged**
