### PR TITLE
issue #130 Oppurtunity cards css enhanced

### PR DESCRIPTION
**Pull request by ronitblenz**
## What is the change?
I have added/changed the following things
 - Font
 - Styled the cards 
 - Made the square logos into circular ones
 - fixed few typos

## Related issue?
closes: #130 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm JWOC contributor.

##  Screenshots (if any)
Screenshot 2022-02-12 at 1 03 53 PM

### CODE REVIEW

**Comment by Chaitalishetty** [comment]
Amazing work @ronitblenz !
But can you make it responsive. 
As the logos are overflowing from the card.
image

**Comment by ronitblenz** [comment]
Actually, I cant make it responsive, I am sorry🙃

**Comment by ronitblenz** [comment]
Could you please merge the PR?

**Comment by Chaitalishetty** [comment]
Then I will merge it but label with easy tag

**Comment by ronitblenz** [comment]
No no wait, I am trying to make it responsive

**Comment by Chaitalishetty** [comment]
Okay fine.

**Pull request merged**
